version: "3.9"
services:
  postgres:
    image: postgres
    container_name: coffee_control
    environment:
      POSTGRES_USER: gabrielcunha
      POSTGRES_PASSWORD: brasil
      PGDATA: /data/postgres
    volumes:
      - /home/951549924@adm.unifor.br/Documentos/CoffeeControl/CoffeeControl/back/coffee_control/volume-docker:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
